### ISSUE TITLE
Translation result returns the same text

### ISSUE THREAD

**Issue by gelodefaultbrain** [ssut/py-googletrans#254] opened 2020-12-08 08:18 UTC
Hello! First of all Thank you for this wonderful python package! It really helps a lot in translating text data with the use of Google Translation. I am amazed on how you do this Thank you!

For now I have an issue and I noticed that when I do a translate `it returns the same text`. Please take this example

```
from googletrans import Translator
translator = Translator() # At direct pip install,this service_url : translate.googleapis.com will not work , this is the indicator that new code had been installed
translated_text = translator.translate("Kto chce się was pozbyć?",src="pl",dest="en")
print(translated_text.text)
print(translator.detect('Tiu frazo estas skribita en Esperanto.').lang)
```

**Output:**
```
Kto chce się was pozbyć?
en
[Finished in 3.0s]
```

I am trying to translate a Polish text and that second one I think is Spanish so yes as you can see there it returns the same :( 
![image](https://user-images.githubusercontent.com/55988471/101457735-d81f9180-3970-11eb-9e64-57933787dd7a.png)

I already tried adding the `service_urls `but still no luck :( 

```
service_urls=[
      'translate.google.com',
      'translate.google.co.kr',
      'translate.googleapis.com'
]
```

When I apply the urls specified it goes back to the FAMOUS error which is 

```
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python38\lib\site-packages\googletrans\gtoken.py", line 63, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
```

Can you please help me Thank you!

**Comment by raviolli** [comment] 2020-12-08 21:33
I believe this is because you are accessing too many requests too often. If you pause for an house then try again it will work.

**Comment by gelodefaultbrain** [comment] 2020-12-09 02:29
Hello! Yess look I tried it out the next day and it's working good

![image](https://user-images.githubusercontent.com/55988471/101565937-136d9f00-3a09-11eb-9ace-0f6b971fd866.png)


May I ask can the devs make a way to somehow prevent this? like update the github repo or hmmm I was thinking if can we just use a `time.sleep(seconds)`    to somehow like trick it for now having to many requests? Thanks!

**Comment by Aya-Ka** [comment] 2020-12-09 02:38
I am facing the same problem, I added `time.sleep(1)` , but it doesn't work...

**Comment by gelodefaultbrain** [comment] 2020-12-09 03:15
Hii :D ohhh so the time.sleep(1) did not work out hmmm...  I had a test run too translating about a 100 texts and it went good but when I did another it returns the same text. Now I had to use this [google_trans_new](https://github.com/lushan88a/google_trans_new). It also uses the Google Translate API. Maybe you might also want to use it :D

**Comment by ssut** [comment] 2020-12-09 14:21
Possible duplicate of #234, and please check this on #255. (`pip install googletrans==4.0.0-rc1`)

**Closed by ssut** 2020-12-09 14:21 UTC

**Comment by gelodefaultbrain** [comment] 2020-12-12 05:33
Thank you! :D

**Comment by jonbesga** [comment] 2021-01-16 18:53
Hi @ssut, I've been looking at #234 and it seems to tackle only the second problem (`AttributeError: 'NoneType' object has no attribute 'group'`)

But it doesn't seem to deal with the "Translation result returns the same text" problem.

I just got this issue today as well. Is there any solution to it?
