### ISSUE TITLE
the symbol × can not be translated correctly.

### ISSUE THREAD

**Issue by wotanzheng** [ssut/py-googletrans#15] opened 2017-04-06 07:11 UTC
You can test it.

**Comment by wotanzheng** [comment] 2017-04-06 08:22
÷has the same problem.

**Comment by ssut** [comment] 2017-04-06 13:58
Fixing the issue related to the special characters.

**Comment by ssut** [comment] 2017-04-07 11:05
I'm going to mark this issue as duplicate of #14 that is an exact duplicate.

**Closed by ssut** 2017-04-07 11:05 UTC
Labels: bug, in progress
