### ISSUE TITLE
Error when calling translator.translate()

### ISSUE THREAD

**Issue by ValleyFish** [ssut/py-googletrans#250] opened 2020-12-03 09:53 UTC
**Googletrans version:**
- [x] **3.x**

**I'm submitting a ...** 

- [x] bug report

**Current behavior:**

**Expected behavior:**
Direct error when calling translation code

**Steps to reproduce:**
Direct error when calling translation code

**Related code:**

```
translator = Translator(service_urls=[
      'translate.google.cn',
    ])
print(translator.translate('안녕하세요.'))
```

**Other information:**
the error tip:code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
my guess: I think the translation interface has changed

**Comment by ssut** [comment] 2020-12-03 10:09
Duplicate of #234.

**Closed by ssut** 2020-12-03 10:09 UTC

**Comment by ValleyFish** [comment] 2020-12-04 02:23
> [＃234](https://github.com/ssut/py-googletrans/issues/234)重复。

sorry
