### ISSUE TITLE
Cannot translated any sentence

### ISSUE THREAD

**Issue by chessgenius** [ssut/py-googletrans#240] opened 2020-11-18 02:20 UTC
**Googletrans version:**
- [ x] **3.x**
- [ ] **2.x**

**I'm submitting a ...** 

- [ x] bug report
- [ ] feature request

**Current behavior:**

I only get 429 error code even I tried to use 200 free proxies. Just happens 2 days ago.
I think it may be because of google changing the token because the token I get for all the proxy is the same, and it always make me get this 429 error for all the proxies.

**Comment by ssut** [comment] 2020-11-18 05:21
Duplicate of #234.

**Closed by ssut** 2020-11-18 05:21 UTC
