### ISSUE TITLE
TokenAcquirer not working anymore

### ISSUE THREAD

**Issue by tobiasblasberg** [ssut/py-googletrans#243] opened 2020-11-18 13:39 UTC
**Googletrans version:**
- [X] **3.0.0**
- [ ] **2.x**

**I'm submitting a ...** 
- [X ] bug report
- [ ] feature request

**Current behavior:**
The following code is not creating valid Google Tokens anymore, which causes blocks after a specific amount of translations. 
```
from googletrans.gtoken import TokenAcquirer
acquirer = TokenAcquirer()
text = 'test'
tk = acquirer.do(text)
tk
```

**Expected behavior:**
Until yesterday, valid tokes where generated. Probably caused by a Google Translate fix.

**Comment by jwa018** [comment] 2020-11-25 19:56
Is this why I get this error? 
``` Traceback (most recent call last):
  File "translate.py", line 20, in <module>
    translated_line = translate_line(line)
  File "translate.py", line 7, in translate_line
    nor_comment = translator.translate(comment, dest='no', src='en')
  File "C:\Users\Bo\Envs\unhealthy-conversations\lib\site-packages\googletrans\client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "C:\Users\Bo\Envs\unhealthy-conversations\lib\site-packages\googletrans\client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "C:\Users\Bo\Envs\unhealthy-conversations\lib\site-packages\googletrans\gtoken.py", line 195, in do
    self._update()
  File "C:\Users\Bo\Envs\unhealthy-conversations\lib\site-packages\googletrans\gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by ssut** [comment] 2020-12-02 13:28
Duplicate of #234.

**Closed by ssut** 2020-12-02 13:28 UTC
