### ISSUE TITLE
'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by gubareve** [ssut/py-googletrans#258] opened 2020-12-10 20:05 UTC
**Googletrans version:**
- [x] **3.x**
- [ ] **2.x**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**

```py
from googletrans import Translator
translator = Translator()
return translator.translate(text='testing', dest='fr').text

Error: AttributeError: 'NoneType' object has no attribute 'group'
```

**Expected behavior:**

The translation succeeds.

**Steps to reproduce:**

Install googletrans 3.0, run the following code:
```py
from googletrans import Translator
translator = Translator()
return translator.translate(text='testing', dest='fr').text
```

**Related code:**

googletrans/gtoken.py is the file causing the error, here is the full stacktrace:

```py

File "/usr/local/lib/python3.7/dist-packages/googletrans/client.py", line 182, in translate
--
12 | data = self._translate(text, dest, src, kwargs)
13 | File "/usr/local/lib/python3.7/dist-packages/googletrans/client.py", line 78, in _translate
14 | token = self.token_acquirer.do(text)
15 | File "/usr/local/lib/python3.7/dist-packages/googletrans/gtoken.py", line 194, in do
16 | self._update()
17 | AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by opennota** [comment] 2020-12-10 20:10
Duplicate of https://github.com/ssut/py-googletrans/issues/234

**Closed** 2020-12-10 20:17 UTC
