### ISSUE TITLE
Googletrans does not work through command line anymore

### ISSUE THREAD

**Issue by KursX** [ssut/py-googletrans#244] opened 2020-11-18 15:51 UTC
translate "veritas lux mea" -s la -d en
[en] veritas lux mea
    ->
[en] veritas lux mea
[pron.] veritas lux mea

translate "text" -s en -d ru
[en] text
    ->
[ru] text
[pron.] text

**Comment by ryanprater** [comment] 2020-11-18 16:05
Duplicate of #241

**Comment by Jiurong-Yang** [comment] 2020-11-19 23:10
Doesn't work anymore for me either, everything is detected to be English. And #241 is closed, even though the problem persists.

**Comment by Jiurong-Yang** [comment] 2020-11-19 23:41
Looks like the default for the code is to not raise an exception and return a dummy data when the request failed with a non 200 status. This is the code I'm getting 
Exception: Unexpected status code "429" from ['translate.google.com']

**Comment by Jiurong-Yang** [comment] 2020-11-20 00:07
Further testing showed using another machine worked fine. Seems like there is a limitation on the IP address.

**Comment by mohamedniyaz1996** [comment] 2020-11-21 16:58
Exactly  this happens for me, When I feed some Input to translate() api , it returns same input as output.

Now , I am thinking , googletrans api returns same input back as output if it faces **error 429 : Too many requests**

Still , I had used proxies like below but same thing happens

```
translator = Translator(service_urls=['translate.google.com', 'translate.google.co.kr'], proxies={{'http': 'http://' + proxy}})
```

where proxy would take values like below:

```
166.88.111.87:8800
192.126.235.76:8800
192.126.244.114:8800
216.158.192.96:8800
```

Please correct me if I am wrong.

**Closed** 2021-01-27 19:50 UTC
Labels: wontfix
