### ISSUE TITLE
Google Trans - Giving me same Input as Output

### ISSUE THREAD

**Issue by mohamedniyaz1996** [ssut/py-googletrans#246] opened 2020-11-20 08:49 UTC
**Googletrans version:**
- **3.x**

**I'm submitting a ...** 

- bug report

**Current behavior:**
I am trying to translate from AWS EC2 Instance with googletrans python library using below snippet:

```from googletrans import Translator
translator = Translator(service_urls=['translate.google.com', 'translate.google.co.kr'])
translated_text = str(translator.translate("你好!", dest="en").text)

print(translated_text) # <------- outputs to 你好! but it should be ideally Hello there
```

Even I tried with proxy like below where I read proxy from file and use it at **translator()** method, but no luck:

```
translator = Translator(service_urls=['translate.google.com', 'translate.google.co.kr'],proxies=proxy)
translated_text = str(translator.translate("你好!", dest="en").text)
print(translated_text)
```

The same code was working for 6+ months at same instance, but from last 2-3 days , I am getting output same as input. 
I checked it **translate.google.com** , it was working fine, so thought it would be a bug with googletrans

**Current Behaviour:**

Suppose if I want to translate 你好! to English , At Output , I am getting same value "你好!" - before that it converts to "Hello there".

**Environment:**

1. Ubuntu 16.04.6 LTS
2. Python 3.7.3
3. GoogleTrans - 3.0.0, httpcore - 0.9.1 , httpx - 0.13.3
4. AWS Region : US_EAST

Please help me to figure out root-cause of this error. The same code works on different machine - is there any limitation on IP?

Even for Single text, this is happening. Any help appreciated, Thanks!

**Comment by noman00910** [comment] 2020-11-20 10:58
Exactly, I am facing the same situation. Is it because of IP? If it is, then there should be proxy support.

**Comment by mohamedniyaz1996** [comment] 2020-11-20 11:25
> Exactly, I am facing the same situation. Is it because of IP? If it is, then there should be proxy support.

Yeah, but need to make sure with contributors even about this.

**Comment by chabo12345** [comment] 2020-11-21 21:18
Hi everyone. 
I have same problem. 
My internet provider is  Telecom MNE.

**Comment by erenturkm** [comment] 2020-11-22 08:12
Same, it worked yesterday but giving the same output as input Today.

**Comment by mohamedniyaz1996** [comment] 2020-11-22 18:18
Here I think, the code is written in a way , that if requests turns out be errored as **429 Too many requests** , then instead of returning the error , it return input as output - Not sure though.

@ssut - Please correct me if I am wrong.

**Comment by tmgcassidy** [comment] 2020-11-23 16:31
Its stopped working for me too, any idea when it will come back online?

**Comment by KryakinVadim** [comment] 2020-11-23 18:01
I have same problem.

**Comment by solus161** [comment] 2020-11-24 01:55
I got this since Sunday

**Comment by RahulARanger** [comment] 2020-11-24 05:34
The simplest solution would be to send as many requests through loops and select the one which is working. It was working for me. But it never took more than 2 sec.

**Comment by mohamedniyaz1996** [comment] 2020-11-24 12:53
> The simplest solution would be to send as many requests through loops and select the one which is working. It was working for me. But it never took more than 2 sec.

Won't it lead to long-time block from Google? Can u share how do u frame translator object inside loop

**Comment by KursX** [comment] 2020-11-24 13:45
Same problem

**Comment by tmgcassidy** [comment] 2020-11-24 13:56
> Here I think, the code is written in a way , that if requests turns out be errored as **429 Too many requests** , then instead of returning the error , it return input as output - Not sure though.
> 
> 
> 
> @ssut - Please correct me if I am wrong.

I think this is what's going on...it started working for me when I changed my IP through a VPN, but it stopped working shortly after that. Google might have lowered its threshold for repeated request blacklists.

**Comment by RahulARanger** [comment] 2020-11-24 14:15
> > The simplest solution would be to send as many requests through loops and select the one which is working. It was working for me. But it never took more than 2 sec.
> 
> Won't it lead to long-time block from Google? Can u share how do u frame translator object inside loop

Google won't block us, and it didn't cause an infinite loop. 

```python
import googletrans
class GT:
    def __init__(self):
        while True:
            self.translator=googletrans.Translator(service_urls=['translate.google.com'])
            try:
                trial=self.translator.detect('Hello there')
                break
            except Exception as e:
                print(e)   # can be commented
    def doThings(self):
        pass
if __name__=='__main__':
    a=GT()
```

**Comment by mohamedniyaz1996** [comment] 2020-11-24 15:42
> > > The simplest solution would be to send as many requests through loops and select the one which is working. It was working for me. But it never took more than 2 sec.
> > 
> > 
> > Won't it lead to long-time block from Google? Can u share how do u frame translator object inside loop
> 
> Google won't block us, and it didn't cause an infinite loop.
> 
> ```python
> import googletrans
> class GT:
>     def __init__(self):
>         while True:
>             self.translator=googletrans.Translator(service_urls=['translate.google.com'])
>             try:
>                 trial=self.translator.detect('Hello there')
>                 break
>             except Exception as e:
>                 print(e)   # can be commented
>     def doThings(self):
>         pass
> if __name__=='__main__':
>     a=GT()
> ```
> 
> The problem was with Object creation so the `Translator` object returns the same as input whenever request fails so first identify the rejected request and ask again.

But even with this code-block, I am getting either of 2 following output scenarios:

1. 'NoneType' object has no attribute 'group'
2. Same Input as Output.

**Comment by KryakinVadim** [comment] 2020-11-24 16:04
solution works but it is bad
`
    for _ in range(10):
        try:
            translator = Translator()
            result = translator.translate(
                text=text,
                src=src,
                dest=dest
            )
            if text != result.text:
                return result.text
        except Exception:
            pass
`

**Comment by KryakinVadim** [comment] 2020-11-24 16:05
solution works but it is bad

    for _ in range(10):
        try:
            translator = Translator()
            result = translator.translate(
                text=text,
                src=src,
                dest=dest
            )
            if text != result.text:
                return result.text
        except Exception as e:
            pass

**Comment by KursX** [comment] 2020-11-25 11:42
The translator does not always give the same translation to the source text. Sometimes it duplicates parts
![image](https://user-images.githubusercontent.com/7107580/100223354-71d84f00-2f2c-11eb-8512-7d0ae0477e3a.png)

**Comment by chabo12345** [comment] 2020-11-28 19:31
Hi everyone,
After I translated few hundred of excel cell(every cell is new request) google send me same output like input, and I'm unable to use googletrans for that day.
When I switched from my WI-FI on mobile hotspot, I can use again google translate for few hundred requests and after that have same output like input.
So my conclusion that Google somehow restrict number of requests to one IP.
Please correct me if I'm wrong.

**Comment by mortalsky** [comment] 2020-12-02 17:23
Having the same issue.

**Comment by mortalsky** [comment] 2020-12-03 07:00
> Having the same issue.

it solved after 4-5 hours. I didn't do anything in these 4-5 hours. It was probably some kind of temp ban.

**Comment by Wikidepia** [comment] 2020-12-03 10:21
Having the same issue, tried with proxy still the same result

**Comment by noman00910** [comment] 2020-12-05 11:37
is this issues is solved yet or not? as @ssut updated the version

**Comment by Mat37** [comment] 2020-12-06 10:58
> 
> 
> is this issues is solved yet or not? as @ssut updated the version

I still have this issue with the updated version

**Comment by tmgcassidy** [comment] 2020-12-07 05:28
> > Having the same issue.
> 
> 
> 
> it solved after 4-5 hours. I didn't do anything in these 4-5 hours. It was probably some kind of temp ban.

I think google's cracking down on the number of requests you can make to try to push people onto their paid service. That's my best guess. I was using this for work, but moved to a service called [DeepL](https://www.deepl.com/docs-api/). If you regularly need to do machine translation, the DeepL API is super easy to use and the translation is actually [more accurate](https://www.at-languagesolutions.com/en/atblog/google-translate-vs-deepl/) than google.

**Comment by ssut** [comment] 2020-12-09 14:21
Possible duplicate of #234, and please check this on #255. (pip install googletrans==4.0.0-rc1)

**Closed by ssut** 2020-12-09 14:21 UTC
