### ISSUE TITLE
google-trans: suddenly breaks

### ISSUE THREAD

**Issue by VikasRajashekar** [ssut/py-googletrans#247] opened 2020-11-21 17:30 UTC
0

Here is the simple code:

```
from googletrans import Translator
translator = Translator()
translator.translate('Hello!! How are you?',dest='de').text
It sometimes works and sometimes throws the exception:
```

```
--------------------------------------------------------------------------- AttributeError Traceback (most recent call last) in 1 from googletrans import Translator 2 translator = Translator() ----> 3 translator.translate('Hello!! How are you?',dest='de').text

~/anaconda3/envs/hugging/lib/python3.8/site-packages/googletrans/client.py in translate(self, text, dest, src, **kwargs) 180 181 origin = text --> 182 data = self._translate(text, dest, src, kwargs) 183 184 # this code will be updated when the format is changed.

~/anaconda3/envs/hugging/lib/python3.8/site-packages/googletrans/client.py in _translate(self, text, dest, src, override) 76 77 def _translate(self, text, dest, src, override): ---> 78 token = self.token_acquirer.do(text) 79 params = utils.build_params(query=text, src=src, dest=dest, 80 token=token, override=override)

~/anaconda3/envs/hugging/lib/python3.8/site-packages/googletrans/gtoken.py in do(self, text) 192 193 def do(self, text): --> 194 self._update() 195 tk = self.acquire(text) 196 return tk

~/anaconda3/envs/hugging/lib/python3.8/site-packages/googletrans/gtoken.py in _update(self) 60 61 # this will be the same as python code after stripping out a reserved word 'var' ---> 62 code = self.RE_TKK.search(r.text).group(1).replace('var ', '') 63 # unescape special ascii characters such like a \x3d(=) 64 code = code.encode().decode('unicode-escape')

**AttributeError: 'NoneType' object has no attribute 'group'**
```

What is the permanent solution for this issue? I have about 10000 lines to be translated and can't afford to skip lines.

I googled for the fix but none of them actually fixed it.

**Comment by tmgcassidy** [comment] 2020-11-23 00:07
Its broken for me too. 

Using the example provided on the https://pypi.org/project/googletrans/ homepage: 

print(translator.translate('안녕하세요.'))
I get the output:
Translated(src=en, dest=en, text=안녕하세요., pronunciation=안녕하세요., extra_data="{'translat...")

and the same output when I try to use:
print(translator.translate('안녕하세요.', dest='en')). Any idea when this will come back up and it will start working again?

**Comment by ssut** [comment] 2020-11-23 01:07
Duplicate of #234.

**Closed by ssut** 2020-11-23 01:07 UTC
