### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by hasff** [ssut/py-googletrans#263] opened 2020-12-14 15:12 UTC
**Googletrans version:**
- [x] **3.x**
- [ ] **2.x**

- Python 3.8.6
- googletrans==3.0.0

**I'm submitting an error** 

- [x] bug report
- [ ] feature request

**Current behavior:**
Traceback (most recent call last):
  File ".\translate.py", line 5, in <module>
    t = trans.translate(
  File "C:\PythonInstall\lib\site-packages\googletrans\client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "C:\PythonInstall\lib\site-packages\googletrans\client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "C:\PythonInstall\lib\site-packages\googletrans\gtoken.py", line 194, in do
    self._update()
  File "C:\PythonInstall\lib\site-packages\googletrans\gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

**Expected behavior:**
A translation.

**Steps to reproduce:**
from googletrans import Translator

trans = Translator()
t = trans.translate(
    'Bom dia para você', src= 'pt', dest='de'
)
print(f'{t.origin} -> {t.text}')

**Other information:**

In googletrans\gtoken.py, 
line 62: self.RE_TKK.search(r.text) <- is returning None
r.text <- have javascript code, couldn't understand why it is not finding and replacing the 'var ' in r.text.

**Comment by ssut** [comment] 2020-12-14 15:26
Duplicate of https://github.com/ssut/py-googletrans/issues/234.

**Closed by ssut** 2020-12-14 15:26 UTC
