### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by NicolasMICAUX** [ssut/py-googletrans#272] opened 2021-02-11 19:07 UTC
in test script, got error :
```
  File "/home/nicolas/Bureau/Projets/translate-server/main.py", line 5, in <module>
    print(translator.translate('The quick brown fox.'))
  File "/home/nicolas/Bureau/Projets/translate-server/venv/lib/python3.8/site-packages/googletrans/client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "/home/nicolas/Bureau/Projets/translate-server/venv/lib/python3.8/site-packages/googletrans/client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "/home/nicolas/Bureau/Projets/translate-server/venv/lib/python3.8/site-packages/googletrans/gtoken.py", line 194, in do
    self._update()
  File "/home/nicolas/Bureau/Projets/translate-server/venv/lib/python3.8/site-packages/googletrans/gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

```

**Comment by MaertHaekkinen** [comment] 2021-02-11 19:35
Looks like a duplicate of [issue 265](https://github.com/ssut/py-googletrans/issues/265).

**Comment by terryyz** [comment] 2021-03-10 16:07
Hi @NicolasMICAUX, please check #280 and see how it goes :)

**Closed by terryyz** 2021-03-10 16:07 UTC

**Comment by NicolasMICAUX** [comment] 2021-03-18 16:56
thx a lot !
